name: sra
description: Dart wrapper to interact with Some Random Api's Rest api. Easy to use features.
version: 0.1.1
homepage: https://github.com/Yakiyo/sra.dart
repository: https://github.com/Yakiyo/sra.dart

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

